# Resolución Numérica de Sistemas de Ecuaciones Lineales


En esta unidad se examinarán métodos directos para resolver el sistema lineal

$$
                   \begin{array}{cccccccccc}
                   E_1:&  a_{11}x_{1} &+& a_{12}x_{2}& + &\cdots&  + &a_{1n}x_{n}& =& b_1 \\ 
                   E_2:&  a_{21}x_{1}& + &a_{22}x_{2}& + &\cdots & +& a_{2n}x_{n}& = &b_2 \\
                   \vdots   & \vdots      &   &  \vdots         &    & &   &   \vdots        &    &  \vdots     \\
                   E_n:&  a_{n1}x_{1} &+& a_{n2}x_{2}& + &\cdots & +& a_{nn}x_{n}& = &b_n
                      \end{array}
$$

Donde $x=(x_1,x_2,\ldots,x_n)^t$, dado $A=(a_{ij})$ con $i,j=1,2,\ldots,n$ y $b=(b_i)$ para $i=1,2,\ldots,n$.

Estas técnicas directas son métodos que proporcionan una respuesta en un número fijo de pasos y solo están sujetos a los errores de redondeo.

Supondremos que $\det(A)\neq 0$, es decir, el sistema tiene solución única.

Utilizaremos operaciones elemntales para simplificar el sistema lineal anterior, estas son:


   * La ecuación $E_i$ puede multiplicarse por una constante $\lambda$ distinta de cero y la ecuación resultante se emplea en vez de $E_i$. Esta operación se denota por $(\lambda E_i)\rightarrow(E_i)$.
   * La ecuación $E_j$ puede multiplicarse por cualquier constante $\lambda$ y sumarse a la ecuación $E_i$, la ecuación resultante se emplea en vez de $E_i$. Esta operación se denota por $(E_i+\lambda E_j)\rightarrow(E_i)$.
   * El orden de las ecuaciones $E_i$ y $E_j$ puede intercambiarse. Esta operación se denota por $(E_i)\leftrightarrow(E_j)$.

Con estas operaciones, podemos transformar un sistema lineal en otro equivalente (mismas soluciones), que puede resolverse fácilmente. 

Ejemplo: 

Consideremos el siguiente sistema de ecuaciones, 

$$\begin{array}{rcl}
   2x+3y+2z & = &7 \\
   x+2y     & = &3\\
   x+y-3z   & = &-1
   \end{array}
$$

* En python escriba la matriz ampliada [A,b] del sistema anterior. 
* Realice las siguiente operación elemental $(E_3 + (-2)*E_2)\rightarrow (E_3)$.

Desarrollo: 

Para poder usar ciertas funciones de python, como la transpuesta de una matriz o el determinante de esta, debemos importar una libreria llamada numpy, a esta librería le llamaremos np. 

In [1]:
import numpy as np 
A=np.array([[2,3,2],[1,2,0,],[1,1,-3]])
b=np.array([[7],[3],[-1]])
print(A)
print('-----------')
print(b)

[[ 2  3  2]
 [ 1  2  0]
 [ 1  1 -3]]
-----------
[[ 7]
 [ 3]
 [-1]]


Para calcular el determinante de una matriz A numpy proporciona una gama de funciones asociadas al álgebra lineal en este caso en particular la función se llama linalg.det() y si queremos escribir la matriz ampliada [A|b] numpy también tiene implemantada una función que permite concatenar matrices.    

In [2]:
d=np.linalg.det(A)
print('El determinante es', d)
Aampl=np.concatenate((A,b),axis=1)
print('La matriz ampliada es:\n ', Aampl)

El determinante es -4.999999999999999
La matriz ampliada es:
  [[ 2  3  2  7]
 [ 1  2  0  3]
 [ 1  1 -3 -1]]


Para invocar la primera fila de  la matriz ampliada, lo hacemos de la sigiuente manera: 

In [3]:
s=Aampl[0,:]
print(s)

[2 3 2 7]


Para realizar la transformación elemental $(E_1 + E_2)\rightarrow (E_2)$, lo podemos hacer así: 

In [4]:
Aampl[1,:]=Aampl[0,:]+(-2)*Aampl[1,:]
print(Aampl)

[[ 2  3  2  7]
 [ 0 -1  2  1]
 [ 1  1 -3 -1]]
